[[redirects]]
  from = "/api/*"
  to = "https://catalogue-cinematica-backend-74ab338129b9.herokuapp.com/:splat"
  status = 200
  force = true

  [[redirects]]
  from = "/account"
  to = "/"
  status = 200
  force = true

  [[redirects]]
  from = "/films"
  to = "/"
  status = 200
  force = true

  [[redirects]]
  from = "/reviews"
  to = "/"
  status = 200
  force = true

  [[redirects]]
  from = "/movie/*"
  to = "/"
  status = 200
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://catalogue-cinematica-backend-74ab338129b9.herokuapp.com"
    Access-Control-Allow-Credentials = "true"