[[redirects]]
  from = "/api/*"
  to = "https://catalogue-cinematica-backend-74ab338129b9.herokuapp.com/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/"
  status = 200
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://catalogue-cinematica-backend-74ab338129b9.herokuapp.com"
    Access-Control-Allow-Credentials = "true"